name: Daily XML Crawling

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche UTC
  workflow_dispatch:      # Permite ejecución manual

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Administración Crawler
        run: python scripts/crawl_administracion.py

      - name: Run BOE Crawler
        run: python scripts/crawl_boe.py

      - name: Download XML files
        run: python scripts/download_xmls.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add urls_*.txt downloads/
          git commit -m "Update crawled URLs and XMLs - $(date +%Y%m%d)" || exit 0
          git push
